[package]
name = "orao-solana-vrf"
version = "0.6.1"
edition = "2021"
authors = ["ORAO Devs <hello@orao.network>"]
homepage = "https://orao.network"
repository = "https://github.com/orao-network/solana-vrf"
license = "Apache-2.0"
keywords = [
    "solana",
    "vrf",
    "randomizer",
    "gamblefi",
    "anchor",
]
description = "ORAO Verifiable Random Function for Solana."

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]
cpi = ["no-entrypoint"]
sdk = ["no-entrypoint", "anchor-client", "ed25519-dalek", "tokio", "thiserror"]
default = ["sdk"]

[dependencies]
base64ct = "1.6.0"
anchor-lang.workspace = true
anchor-spl.workspace = true
anchor-client = { workspace = true, optional = true }
ed25519-dalek = { workspace = true, optional = true }
tokio = { version = "1", optional = true }
thiserror = { version = "1", optional = true }
bs58.workspace = true

[dev-dependencies]
byteorder = "1.4.3"
solana-cli-config.workspace = true
rand.workspace = true
anchor-client = { workspace = true, features = ["debug"] }

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
